Add .git to Mapper dependency package.
This was causing problem when this package is included as a dependency
along side Mapper. If the parent project has .git on the Mapper URL
SPM gets confused and throws an error like this:

> error: rename error: Directory not empty (66): /Users/me/Example/Packages/Mapper -> /Users/me/Example/Packages/Mapper-0.14.0